name: Node.js Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.0'

    - name: Install dependencies
      run: npm install

    - name: Start Node.js application
      run: node app.js
